### PR TITLE
Add t_SNE_overview

### PR DESCRIPTION
**Pull request by dhilarj2**
This adds t_SNE_overview.rmd

### CODE REVIEW

**Comment by sachit-kumar** [comment]
Please create your own branch. Do not submit a pull request from master. Refer to https://edav.info/github.html#fixing-mistakes

**Comment by sachit-kumar** [comment]
@dhilarj2 Please make the requested changes so we can merge your pull request. thanks!

**Comment by dhilarj2** [comment]
Hi Sachit,

I've resubmitted the pull request from a different branch!  See https://github.com/jtr13/cc19/pull/164

Arjun

**Comment by sachit-kumar** [comment]
@bojum 
This pull request is re raised as https://github.com/jtr13/cc19/pull/164 . So please close this request.

**Pull request closed without merging**
