### PR TITLE
Add gantt_chart.Rmd CC75

### PR DESCRIPTION
**Pull request by harish-cu**
This PR is a request to merge our community contribution topic, which is an article/brief tutorial on Gantt charts. We added a file named gantt_chart.Rmd that demonstrates two methods of creating Gantt charts - one using geom_line and another using a package called plan. We used our community contribution timelines as sample data for the illustration.

### CODE REVIEW

**Comment by rohitdalal** [comment]
Hi Phani and Harish, there's nothing you need to do right now. The label is for our reference only. 
[bug:extracat not working. ]

**Comment by rohitdalal** [comment]
@bojum  Looks like "Extracat" is not used within this project's rmd file. Looks like when Phani and Harish forked repo it was already there in the description file.

**Comment by bojum** [comment]
All students' projects will be using the same DESCRIPTION file. One of them needs extracate package so the package has to be in DESCRIPTION. I'll add it back. However, the bug about this package should be fixed. The failure you see may be from another bug, which is being fixed right now.

**Comment by jtr13** [comment]
It should be fixed now... see the updated [.travis.yml](https://github.com/jtr13/cc19/blob/master/.travis.yml#L15) file which contains extracat

**Comment by bojum** [comment]
🎉 @harish-cu your work has been featured on the class [website](https://jtr13.github.io/cc19/gantt-charts.html). Thanks for your contribution!

**Pull request merged**
