### PR TITLE
googleVis community contribution 18

### PR DESCRIPTION
**Pull request by junyji**
Community Contribution for Alex Wan and Junyang Jiang (2/2)

### CODE REVIEW

**Review by kmsingh-git — CHANGES_REQUESTED** [review]
The .Rmd filenames in the project repo should be words only and joined with underscores, i.e. Do not include whitespace in the name.

**Comment by junyji** [comment]
> The .Rmd filenames in the project repo should be words only and joined with underscores, i.e. Do not include whitespace in the name.

Thanks. Fixed!

**Review by kmsingh-git — APPROVED** [review]

**Comment by kmsingh-git** [comment]
This passes Travis checks. Looks good from my side

**Comment by bojum** [comment]
🎉 Thanks for your contribution! The branch has been merged.

**Pull request merged**
