### PR TITLE
Stamen Maps with ggmap

### PR DESCRIPTION
**Pull request by Mrugankakarte**
This is contribution to edav.info section 17. Added examples to use `stamen_map()` with `ggmap`, open source alternative to Google Maps API

### CODE REVIEW

**Review by skyetim — CHANGES_REQUESTED** [review]
data folder should be put under `resource/ggmaps`.

**Comment by Mrugankakarte** [comment]
like resources/ggmap/data/xyz.csv or just resources/ggmap/xyz.csv?

**Comment by skyetim** [comment]
That's your call. As long as your files other than the main `Rmd` are in your own `resources/ggmap` folder, I will merge your pull request.

**Comment by Mrugankakarte** [comment]
Ok..moved the data

**Review by skyetim — APPROVED** [review]

**Comment by skyetim** [comment]
🎉 Congrats! Your branch has been merged into master branch.

**Comment by Mrugankakarte** [comment]
Thanks !! :)

**Pull request merged**
