### PR TITLE
pull request from cc group 47

### PR DESCRIPTION
**Pull request by evelynguozy**
My group member and I created a tutorial about different ways of drawing the U.S. map.

### CODE REVIEW

**Comment by jtr13** [comment]
Hi, can you please remove the "setup" label from the first chunk? Thanks!

**Comment by evelynguozy** [comment]
remove setup

**Comment by jtr13** [comment]
Your .Rmd is failing to render both for me locally and on Travis (https://travis-ci.com/jtr13/cc19/builds/135681960) I believe the problem is that additional files are needed besides the `.shp` file in resources. Can you check and add in any missing files? Thanks.

**Comment by jtr13** [comment]
Hi, Can you please check about missing shape files--see comment above--so we can merge this PR?  Thanks!

**Comment by jtr13** [comment]
I believe you're missing the .shx , and .dbf files.

**Comment by evelynguozy** [comment]
add two needed files and update .rmd

**Comment by jtr13** [comment]
:tada: Your pull request has been merged! Thank you for your contribution.

**Pull request merged**
