### PR TITLE
Hojin Lee and Hyuk Joon Kwon

### PR DESCRIPTION
**Pull request by hjlee9295**
Intro to Ridgeline plot  for EDAV community Contribution. - Hojin Lee (hl3328) & Hyuk Joon Kwon (hk3084)

### CODE REVIEW

**Comment by skyetim** [comment]
Hojin and Hyuk, don't worry. There's nothing you need to do right now. 

@jtr13 ucidata cannot be added from DESCRIPTION. It will cause travis stop building.

**Comment by jtr13** [comment]
Sorry, forgot to mention that github packages have to be added to the `.travis.yml` file, not DESCRIPTION. See here for the formatting: https://github.com/jtr13/EDAV/blob/master/.travis.yml

**Comment by jtr13** [comment]
(Also, the indentation has to be perfect in the `.travis.yml` file or it won't work.)

**Comment by jtr13** [comment]
🎉 Congratulations on being the first contribution! Well done everyone!

**Pull request merged**
