### PR TITLE
Add part

### PR DESCRIPTION
**Pull request by jtr13**
missing from ice cream survey file

### CODE REVIEW

**Comment by jtr13** [comment]
@rohitdalal Note that to create a new part, you have to add a line to the beginning of the first chapter in the part.

**Comment by jtr13** [comment]
@bojum @skyetim @Yingyu-Cao Would it work better not to try to organize the chapters as we go to avoid merge conflicts, as you indicated was the case with the DESCRIPTION file?

**Comment by bojum** [comment]
Since each PR adds at most one line to _bookdown.yml, it should not suffer the same problem as in DESCRIPTION. So, either organizing now or later works for me.

**Comment by jtr13** [comment]
@bojum Thanks. I'm still going to close this and make suggestions about the organization once the bulk of the PRs are done.

**Pull request closed without merging**
