### PR TITLE
Add data_ink.rmd

### PR DESCRIPTION
**Pull request by liuhz0926**
Adding data_ink.rmd file from group cc29. So sorry for the delays. Professor Robbins granted us the extension. Please understand. Let me know if there is any questions! Thanks.

### CODE REVIEW

**Comment by kmsingh-git** [comment]
Forgot to comment, this passes Travis checks too. Looks good to me

**Comment by bojum** [comment]
🎉 Merged! Thanks for your contribution!

**Comment by liuhz0926** [comment]
I see that on the CC book, section 36, our project ends at 36.9. But 36.10 to 15 talk about ARIMA is from another group...I guess they belongs to another new sections. Thanks.

**Comment by bojum** [comment]
Thanks for letting us know. We'll look into it.

**Pull request merged**
