### PR TITLE
Group42_Tiffany_Zhu_Olivia_Wang

### PR DESCRIPTION
**Pull request by Olivia98Wang**
Midsemester review on data transformation, visualization and plotting.

### CODE REVIEW

**Review by RandomWalker300 — CHANGES_REQUESTED** [review]
1. line 5: please remove "setup", thanks

**Comment by Olivia98Wang** [comment]
Thank you so much for letting me know! I have removed setup in the updated rmd file.

**Comment by skyetim** [comment]
@jtr13 grid package is imported by `grid.raster` cannot be found by travis.

**Comment by jtr13** [comment]
I'll look into this.

**Comment by jtr13** [comment]
The simplest solution here is to change the way in which images are included to the (more common) markdown syntax, outside of the code chunks:

 \!\[\]\(resources/midsemester_review/1_intro_image.png\)

(The `.Rmd` worked fine for me locally as it should since `grid.raster()` is a function in the **grid** package and there is a call to `library(grid)` in the first chunk.  Add to the list of Travis mysteries...)

**Review by RandomWalker300 — COMMENTED** [review]
would you mind adding the path of your additional resources to your .Rmd?  Thank you!
For example,
``
``
....

"The simplest solution here is to change the way in which images are included to the (more common) markdown syntax, outside of the code chunks:

``

(The .Rmd worked fine for me locally as it should since grid.raster() is a function in the grid package and there is a call to library(grid) in the first chunk. Add to the list of Travis mysteries...)"

**Comment by skyetim** [comment]
🎉 Congrats! Your contribution has been merged!

**Comment by Olivia98Wang** [comment]
Thank you!!!

**Pull request merged**
