### PR TITLE
ggmaps content modification

### PR DESCRIPTION
**Pull request by Mrugankakarte**
I have updated the maps.Rmd file with some minor changes to the content

### CODE REVIEW

**Comment by bojum** [comment]
🎉 Merged! Thanks @Mrugankakarte and @sachit-kumar.

**Comment by Mrugankakarte** [comment]
Thank You!! Just one question, I don't see the changes in book https://jtr13.github.io/cc19/stamen-maps-with-ggmap.html

**Comment by bojum** [comment]
What do you mean by changes? Do you mean the content is not updated?

**Comment by Mrugankakarte** [comment]
yeah. In this PR I had modified some content, I can't see the new content, still shows the old content.

**Comment by bojum** [comment]
try clearing cache or refreshing the site?

**Comment by bojum** [comment]
This is what I see. Is it the updated version?

Screen Shot 2019-11-01 at 11 09 05 PM

**Comment by Mrugankakarte** [comment]
It's there now, I couldn't see it until now. Sorry.

**Comment by bojum** [comment]
No worries! And thanks for checking!

**Pull request merged**
