### PR TITLE
World heatmap plotly

### PR DESCRIPTION
**Pull request by Harguna**

### CODE REVIEW

**Comment by jtr13** [comment]
Hi, thanks for your contribution.  Can you please remove the `.gitkeep` file (or explain why it's needed)? Also, a shorter title work better with the table of contents. Can you change the title to "Plotly world heatmap" or something similar?

**Comment by Harguna** [comment]
Updated the files with changes, as requested.

**Comment by jtr13** [comment]
@skyetim @bojum @Yingyu-Cao OK to merge?

**Comment by jtr13** [comment]
🎉 Your contribution has been merged!

**Pull request merged**
