### PR TITLE
Remove rendered book

### PR DESCRIPTION
**Pull request by jtr13**
Locally rendered versions of the book -- those in the _book folder -- should not be included in the GitHub repo. I've removed them and added _book to .gitignore.

### CODE REVIEW

**Comment by skyetim** [comment]
I don't know how travis works, but this _book folder is what I previously used as the root directory for `gh-pages` branch. Will removing _book folder affect the rendering online?

**Comment by jtr13** [comment]
Not at all.  Travis renders in a separate environment and pushes directly to gh-pages, not to the master branch. The material in the _book folder is old. Admins will render locally to the _book folder to test out pull requests but we don't want those tests to go under version control.

**Comment by skyetim** [comment]
It makes sense! Then we should remove the entire `_book` folder right? It seems that this commit still keeps `sample_project.html` and `search_index.json`.

**Comment by jtr13** [comment]
Yes, you're right. I think the issue is that I added _book to .gitignore before deleting all the files. Will close this and try again.

**Pull request closed without merging**
